// <auto-generated />
namespace DAN_XLII_Kristina_Garcia_Francisco.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class worker : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(worker));
        
        string IMigrationMetadata.Id
        {
            get { return "202006301321285_worker"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
